### ISSUE TITLE
deno-solid: Cannot find package.json

### ISSUE THREAD

**Issue by drewbitt** [bluwy/create-vite-extra#12]
`deno run -A --unstable npm:create-vite-extra --template deno-solid deno-solid`

Scaffolding project in C:\Users\drewbitt\GitHub\MyStuff\deno-solid...

Done. Now run:

  cd deno-solid
  deno task dev

PS C:\Users\drewbitt\GitHub\MyStuff> cd .\deno-solid\
PS C:\Users\drewbitt\GitHub\MyStuff\deno-solid> `deno task dev`
```Task dev deno run -A --unstable --node-modules-dir npm:vite
error when starting dev server:
Error: Cannot find package.json from C:\Users\drewbitt\GitHub\MyStuff\deno-solid
    at crawlFrameworkPkgs (file:///C:/Users/drewbitt/GitHub/MyStuff/deno-solid/node_modules/.deno/vite-plugin-solid@2.4.0/node_modules/vitefu/src/index.js:17:11)
    at async config (file:///C:/Users/drewbitt/GitHub/MyStuff/deno-solid/node_modules/.deno/vite-plugin-solid@2.4.0/node_modules/vite-plugin-solid/dist/esm/index.mjs:52:31)
    at async runConfigHook (file:///C:/Users/drewbitt/GitHub/MyStuff/deno-solid/node_modules/.deno/vite@3.2.3/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:62865:25)
    at async resolveConfig (file:///C:/Users/drewbitt/GitHub/MyStuff/deno-solid/node_modules/.deno/vite@3.2.3/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:62374:14)
    at async createServer (file:///C:/Users/drewbitt/GitHub/MyStuff/deno-solid/node_modules/.deno/vite@3.2.3/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:61636:20)
    at async CAC.<anonymous> (file:///C:/Users/drewbitt/GitHub/MyStuff/deno-solid/node_modules/.deno/vite@3.2.3/node_modules/vite/dist/node/cli.js:707:24)
```
PS C:\Users\drewbitt\GitHub\MyStuff\deno-solid> deno -V
deno 1.27.2

**Comment by bluwy** [comment]
This is an upstream issue in vite-plugin-solid that was previously changed. I've sent a PR to fix it.

**Comment by bluwy** [comment]
Closing this for now as this now depends on an upstream fix.
