### ISSUE TITLE
deno-preact example doesn't work

### ISSUE THREAD

**Issue by scarf005** [bluwy/create-vite-extra#67]
## System info

```
scarf@fedora /r/m/h/s/r/e/vite-project> deno --version
deno 2.1.4 (stable, release, x86_64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2
```

## Reproduction

```
deno run -A npm:create-vite-extra
✔ Project name: … vite-project
✔ Select a template: › deno-preact
✔ Select a variant: › TypeScript
```

when opening localhost:5173, following errors appear:

```
scarf@fedora /r/m/h/s/r/e/vite-project [1]> deno task dev
Task dev deno run -A --node-modules-dir npm:vite

  VITE v5.4.11  ready in 247 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
오후 9:53:09 [vite] Pre-transform error: Cannot find package '@babel/plugin-transform-react-jsx-development' imported from /run/media/home/scarf/repo/etc/vite-project/babel-virtual-resolve-base.js
오후 9:53:09 [vite] Internal server error: Cannot find package '@babel/plugin-transform-react-jsx-development' imported from /run/media/home/scarf/repo/etc/vite-project/babel-virtual-resolve-base.js
  Plugin: vite:preact-jsx
  File: /run/media/home/scarf/repo/etc/vite-project/src/main.tsx
      at __node_internal_ (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:225:9)
      at new NodeError (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:195:5)
      at packageResolve (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:899:9)
      at moduleResolve (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:939:18)
      at defaultResolve (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1017:15)
      at resolve (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1030:12)
      at tryImportMetaResolve (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/files/plugins.js:148:45)
      at resolveStandardizedNameForImport (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/files/plugins.js:173:19)
      at resolveStandardizedName (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/files/plugins.js:185:22)
      at loadPlugin (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/files/plugins.js:55:7)
      at undefined
      at createDescriptor (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
      at undefined
      at step (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:261:32)
      at evaluateAsync (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:291:5)
      at /run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:44:11
      at undefined
      at Function.async (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:43:15)
      at Function.all (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:216:13)
      at undefined
      at createDescriptors (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
      at undefined
      at createPluginDescriptors (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
      at undefined
      at /run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-descriptors.js:65:32
      at undefined
      at Function.<anonymous> (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
      at undefined
      at step (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:269:25)
      at evaluateAsync (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:291:5)
      at Function.errback (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:113:7)
      at errback (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/gensync-utils/async.js:65:18)
      at async (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:188:17)
      at onFirstPause (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:216:13)
      at undefined
      at cachedFunction (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/caching.js:52:46)
      at undefined
      at mergeChainOpts (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-chain.js:349:34)
      at undefined
      at chainWalker (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-chain.js:316:14)
      at undefined
      at buildRootChain (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-chain.js:56:36)
      at undefined
      at loadPrivatePartialConfig (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/partial.js:72:62)
      at undefined
      at loadFullConfig (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/full.js:36:46)
      at undefined
      at transform (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/transform.js:20:44)
      at undefined
      at step (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:269:25)
      at evaluateAsync (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:291:5)
      at /run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:93:9
      at undefined
      at async (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:92:14)
      at stopHiding - secret - don't use this - v1 (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
      at transformAsync (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/transform.js:45:77)
      at TransformPluginContext.transform (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/@preact+preset-vite@2.9.3/node_modules/@preact/preset-vite/dist/esm/index.mjs:77:34)
      at PluginContainer.transform (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49097:19)
      at loadAndTransform (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51929:49)
      at eventLoopTick (ext:core/01_core.js:175:7)
      at async viteTransformMiddleware (/run/media/home/scarf/repo/etc/vite-project/node_modules/.deno/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:61881:24)
```

## workaround

```sh
deno add npm:@babel/plugin-transform-react-jsx-development
deno add npm:babel-plugin-transform-hook-names
```

**Comment by bluwy** [comment]
Looks like this has been fixed in the upstream issue above, so I'll close this for now. The current semver ranges should allow installing the latest `@preact/preset-vite` version.
